modified run_silicon changed the bands.x input file (si.bands.in) to reflect changes in the QE for bands.x input from: &ppintput to: &bands

diff --git a/silicon/run_silicon b/silicon/run_silicon
--- a/silicon/run_silicon
+++ b/silicon/run_silicon
@@ -1,5 +1,14 @@
 #!/bin/sh
-
+# function to test the exit status of a job
+check_failure () {
+    # usage: check_failure $?
+    if test $1 != 0
+    then
+        $ECHO "Error condition encountered during test: exit status = $1"
+        $ECHO "Aborting"
+        exit 1
+    fi
+}
 # run from directory where this script is
 cd `echo $0 | sed 's/\(.*\)\/.*/\1/'` # extract pathname
 EXAMPLE_DIR=`pwd`
@@ -227,7 +236,7 @@ $ECHO " done"
 
 # post-processing for band structure
 cat > si.bands.in << EOF
- &inputpp
+ &bands
     prefix  = 'si'
     outdir = '$TMP_DIR/'
     filband = 'sibands.dat'
